# -*- coding: utf-8 -*-
"""ProjetoA3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L_DO_J3huwoGGHBH8ldOuWA4oIPMav7T
"""

# Commented out IPython magic to ensure Python compatibility.
# Bloco 1
#Importando as bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

# Bloco 2
# lendo o arquivo Global Economy Indicators.csv
GlobEI = pd.read_csv('Global Economy Indicators.csv')

#bloco 3
# Exibindo as colunas
GlobEI.columns

# Bloco 4
# Conhecendo melhor o arquivo
GlobEI.shape

# Bloco 5
# Conhecendo a Cara do arquivo
GlobEI.head()

# Bloco 6
# Identificando os tipos de cada Variavel
GlobEI.dtypes

# Bloco 7
# Identificando medias, máximos e mínimos
GlobEI.describe()

# Bloco 8
# Excluir a coluna Changes in inventories
GlobEI.drop(' Changes in inventories ', axis=1, inplace=True)

# Bloco 9
# Excluir espaços extras nas colunas, inicio e fim da Descrição.
GlobEI.columns = GlobEI.columns.str.strip()

# Bloco 10
# Identificando o arquivo após a exclusão da coluna
GlobEI.head()

# Bloco 11
# Histograma da variavel target PIB
import matplotlib.pyplot as plt

GlobEI.hist(column='Gross Domestic Product (GDP)',bins = 30)
plt.show()

# Bloco 12
# Preparando o Histograma do BRASIL
dadospibbrasil = GlobEI.loc[GlobEI['Country']==' Brazil ']
dadospibbrasil.head()

# Bloco 13
# Histograma do BRASIL do PIB por Ano
ano = dadospibbrasil['Year']
valor = dadospibbrasil['Gross Domestic Product (GDP)']
plt.scatter(ano,valor)
plt.show()

# Bloco 14
# Modelagem - iniciando a Arvore de Decisão
# Classificação do PIB com base no FMI (Fundo Monetário Internacional)
# 0 - PIB Baixo até US$ 100 bilhões
# 1 - PIB Médio US$ 100 bilhões até US$ 1 trilhão
# 2 - PIB Alto acima de US$ 1 trilhão

def classificar_pib(valor):

    if valor < 100_000_000_000:
        return 0   # PIB Baixo

    elif valor < 1_000_000_000_000:
        return 1   # PIB Médio

    else:
        return 2   # PIB Alto

# Bloco 15
# Aplicando ao data Frame
GlobEI['Classe_Economia'] = GlobEI[
    'Gross Domestic Product (GDP)'
].apply(classificar_pib)

# Bloco 16
# X -Atributo e Y - variavel alvo (target)
X = GlobEI[['Gross Domestic Product (GDP)']]
y = GlobEI['Classe_Economia']

# Bloco 17
# Definindo proporção usadas para teste 25% e 75% de treino.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

# Bloco 18
# Previsões usando o método predict
from sklearn import tree
clf = tree.DecisionTreeClassifier(criterion='entropy', max_depth=3)
clf = clf.fit(X_train, y_train)
predictions = clf.predict(X_test)

# Bloco 19
# Matriz de Confusão
print("\nMatriz de confusão detalhada:\n", pd.crosstab(y_test, predictions, rownames=['Real'], colnames=['Predito'], margins=True, margins_name='Todos'))

# Bloco 20
# Medidas usadas em avaliação:
import sklearn.metrics as metrics
print("Relatório sobre a Classificação:\n")
print(metrics.classification_report(y_test, predictions, target_names=['PIB Baixo', 'PIB Médio', 'PIB Alto']))

# Bloco 21
# Árvore para o formato Graphviz
import graphviz
dot_data = tree.export_graphviz(clf, out_file=None)
graph = graphviz.Source(dot_data)
graph.render("Class")
dot_data = tree.export_graphviz(clf, out_file=None, feature_names=X.columns, class_names=['PIB Baixo', 'PIB Médio', 'PIB Alto'], filled=True, rounded=True, special_characters=True)
graph = graphviz.Source(dot_data, format="png")
graph

# Bloco 22
# X -Atributo e Y - variavel alvo (target)
X = GlobEI[['Gross Domestic Product (GDP)']]
y = GlobEI['Classe_Economia']

# Bloco 23
# treino e teste Gaussiano
(X_train, X_test, y_train, y_test) = train_test_split(X,y)

# Bloco 24
# Modelagem - iniciando Naives Bayes (Divisão de 3 tipos de PIB)
# Modelo 1 classificador Gaussiano
from sklearn.naive_bayes import GaussianNB

# instanciando o modelo
modelo1 = GaussianNB()

# treinando o modelo utilizando o conjunto de treino
modelo1.fit(X_train,y_train)

# validando o modelo utilizando o conjunto de teste
acuracia1 = str(round(modelo1.score(X_test,y_test) * 100, 2))+"%"

# Bloco 25
# imprimindo o resultado
print("A acurácia do modelo 1 foi",acuracia1)

# Bloco 26
# Modelo 2 classificador Multinomial
from sklearn.naive_bayes import MultinomialNB

# instanciando o modelo
modelo2 = MultinomialNB()

# treinando o modelo utilizando o conjunto de treino
modelo2.fit(X_train,y_train)

# validando o modelo utilizando o conjunto de teste
acuracia2 = str(round(modelo2.score(X_test,y_test) * 100, 2))+"%"

# Bloco 27
# imprimindo o resultado
print("A acurácia do modelo 2 foi",acuracia2)

# Bloco 28
# Modelo 3 classificador Bernoulli
from sklearn.naive_bayes import BernoulliNB

# instanciando o modelo
modelo3 = BernoulliNB()

# treinando o modelo utilizando o conjunto de treino
modelo3.fit(X_train,y_train)

# validando o modelo utilizando o conjunto de teste
acuracia3 = str(round(modelo3.score(X_test,y_test) * 100, 2))+"%"

# Bloco 29
# imprimindo o resultado
print("A acurácia do modelo 3 foi",acuracia3)

# Bloco 30
# Modelagem - iniciando KNN (Divisão de 3 tipos de PIB)
# Bibliotecas
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix

# Bloco 31# X -Atributo e Y - variavel alvo (target)
X = GlobEI[['Gross Domestic Product (GDP)']]
y = GlobEI['Classe_Economia']

# Bloco 32
# treino e teste
(X_train, X_test, y_train, y_test) = train_test_split(X,y)

# Bloco 33
# instanciando o modelo
modelo = KNeighborsClassifier()

# treinando o modelo utilizando o conjunto de treino
modelo.fit(X_train,y_train)

# validando o modelo utilizando o conjunto de teste
acuracia = str(round(modelo.score(X_test,y_test) * 100, 2))+"%"

# imprimindo o resultado
print("A acurácia do modelo k-NN foi",acuracia)

# Bloco 34
# predizendo o teste
y_pred = modelo.predict(X_test)

# comparando predição com o real
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred, target_names=['PIB Baixo', 'PIB Médio', 'PIB Alto']))
confusion_matrix(y_test, y_pred)

# Bloco 35
# Grafico para visualizar a distribuição dos PIBs - Curva de concentração de dados (KERNEL DENSITY ESTIMATION)
GlobEI['PIB_LOG'] = np.log1p(
    GlobEI['Gross Domestic Product (GDP)']
)

sns.pairplot(
    GlobEI,
    hue='Classe_Economia',
    vars=['PIB_LOG'],
    diag_kind='kde'
)

plt.show()

# Bloco 36
# APLICANDO O ALGORITMO DA ÁRVORE DE DECISÃO #
from sklearn import tree
modeloARV = tree.DecisionTreeClassifier(criterion='entropy', max_depth=3)
modeloARV = modeloARV.fit(X_train, y_train)
predictionsARV = modeloARV.predict(X_test)

# MOSTRANDO OS RESULTADOS DO ALGORITMO DA ÁRVORE DE DECISÃO #

print("\nMatriz de confusão detalhada da Árvore de Decisão:\n",
      pd.crosstab(y_test, predictionsARV, rownames=['Real'], colnames=['Predito'],
      margins=True, margins_name='Todos'))

dic_arv = metrics.classification_report(y_test, predictionsARV, target_names=['PIB Baixo', 'PIB Médio', 'PIB Alto'],output_dict=True)
result_arv = dic_arv['accuracy']
print("Acurácia da Árvore de Decisão: ", result_arv)

# Bloco 37
# APLICANDO O ALGORITMO KNN #

from sklearn.neighbors import KNeighborsClassifier

modeloKNN = KNeighborsClassifier(n_neighbors=3)
modeloKNN.fit(X_train, y_train)
predictionsKNN = modeloKNN.predict(X_test)

# MOSTRANDO OS RESULTADOS DO ALGORITMO KNN #

print("\nMatriz de confusão detalhada do KNN:\n",
      pd.crosstab(y_test, predictionsKNN, rownames=['Real'], colnames=['Predito'],
      margins=True, margins_name='Todos'))

dic_knn = metrics.classification_report(y_test, predictionsKNN, target_names=['PIB Baixo', 'PIB Médio', 'PIB Alto'],output_dict=True)
result_knn = dic_knn['accuracy']
print("Acurácia do KNN: ", result_knn)

# Bloco 38
# APLICANDO O ALGORITMO NAIVES #

from sklearn.naive_bayes import GaussianNB

modeloNAIVES = GaussianNB()
modeloNAIVES.fit(X_train, y_train)
predictionsNAIVES = modeloNAIVES.predict(X_test)

# MOSTRANDO OS RESULTADOS DO ALGORITMO NAIVES #

print("\nMatriz de confusão detalhada do NAIVES:\n",
      pd.crosstab(y_test, predictionsNAIVES, rownames=['Real'], colnames=['Predito'],
      margins=True, margins_name='Todos'))

dic_NAIVES = metrics.classification_report(y_test, predictionsNAIVES, target_names=['PIB Baixo', 'PIB Médio', 'PIB Alto'],output_dict=True)
result_NAIVES = dic_NAIVES['accuracy']
print("Acurácia do NAIVES: ", result_NAIVES)

# Bloco 39
# COMITÊ DE CLASSIFICADORES

print("COMITÊ DE CLASSIFICADORES")

# Exemplo de PIB para classificação com PIB de 500 bilhões.
novo_pib = pd.DataFrame({
    'Gross Domestic Product (GDP)': [500000000000]
})

tot_baixo = 0
tot_medio = 0
tot_alto = 0

# ÁRVORE DE DECISÃO
pred_arv = modeloARV.predict(novo_pib)[0]

if pred_arv == 0:
    tot_baixo += 1
elif pred_arv == 1:
    tot_medio += 1
else:
    tot_alto += 1

print("Árvore de Decisão:", pred_arv)

# KNN
pred_knn = modeloKNN.predict(novo_pib)[0]

if pred_knn == 0:
    tot_baixo += 1
elif pred_knn == 1:
    tot_medio += 1
else:
    tot_alto += 1

print("KNN:", pred_knn)

# NAIVE BAYES
pred_nb = modeloNAIVES.predict(novo_pib)[0]

if pred_nb == 0:
    tot_baixo += 1
elif pred_nb == 1:
    tot_medio += 1
else:
    tot_alto += 1

print("Naive Bayes:", pred_nb)

# RESULTADO FINAL

print("\nTotal de votos:")
print("PIB Baixo =", tot_baixo)
print("PIB Médio =", tot_medio)
print("PIB Alto  =", tot_alto)

if tot_baixo >= 2:
    print("\nO comitê acredita que a economia possui PIB BAIXO.")

elif tot_medio >= 2:
    print("\nO comitê acredita que a economia possui PIB MÉDIO.")

else:
    print("\nO comitê acredita que a economia possui PIB ALTO.")

# Verifica unanimidade

if tot_baixo == 3:
    print("O comitê foi unânime: PIB BAIXO.")

elif tot_medio == 3:
    print("O comitê foi unânime: PIB MÉDIO.")

elif tot_alto == 3:
    print("O comitê foi unânime: PIB ALTO.")